### PR TITLE
Continents and maps endpoints

### PR DESCRIPTION
**Pull request by Mikayex**
Related issue: #19

### CODE REVIEW

**Comment by greaka** [comment]
That's quite the complex endpoints, but the code is looking good!
Would you add a `From` impl on the floor/continent id using a tuple?
That way you could fetch it like this: `let foo: Floor = client.single((0, 12))?;`
Putting a test for that in would also help discoverability for that pattern.

**Comment by Mikayex** [comment]
Good idea! However, the best I could do is `let foo: Floor = client.single((0, 12).into())?;` because the `single` function use the tuple as the `IdType` otherwise:
<details>
<summary>Errors without .into()</summary>

```
error[E0277]: `({integer}, {integer})` doesn't implement `std::fmt::Display`
  --> http\tests\continents.rs:37:38
   |
37 |     let floor: Floor = client.single((1, 12)).unwrap();
   |                               ------ ^^^^^^^ `({integer}, {integer})` cannot be formatted with the default formatter
   |                               |
   |                               required by a bound introduced by this call
   |
   = help: the trait `std::fmt::Display` is not implemented for `({integer}, {integer})`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
note: required by a bound in `single`
  --> http\src\client\blocking.rs:71:12
   |
71 |         I: Display + DeserializeOwned + Hash + Send + Sync + Clone + 'static,
   |            ^^^^^^^ required by this bound in `Requester::single`


error[E0271]: type mismatch resolving `<Floor as EndpointWithId>::IdType == ({integer}, {integer})`
  --> http\tests\continents.rs:37:31
   |
37 |     let floor: Floor = client.single((1, 12)).unwrap();
   |                               ^^^^^^ expected tuple, found struct `ContinentFloorId`
   |
   = note: expected tuple `({integer}, {integer})`
             found struct `ContinentFloorId`
note: required by a bound in `single`
  --> http\src\client\blocking.rs:70:68
   |
70 |         T: DeserializeOwned + Clone + Send + Sync + EndpointWithId<IdType = I> + 'static,
   |                                                                    ^^^^^^^^^^ required by this bound in `Requester::single`
```
</details>

I also tried to change the `single` function like so but then other errors popped.
```rust
    fn single<
        T: DeserializeOwned + Clone + Send + Sync + EndpointWithId<IdType = I> + 'static,
        I: Display + DeserializeOwned + Hash + Send + Sync + Clone + 'static,
        Id: Into<I>,
    >(
        &self,
        id: Id,
    ) -> EndpointResult<T> {
        block(Req::single(self, id.into()))
    }
```

<details>
<summary>Example error</summary>

```
error[E0277]: the trait bound `u32: From<i32>` is not satisfied
  --> http\tests\continents.rs:19:42
   |
19 |     let tyria: Continent = client.single(1).unwrap();
   |                                   ------ ^ the trait `From<i32>` is not implemented for `u32`
   |                                   |
   |                                   required by a bound introduced by this call
   |
   = help: the following other types implement trait `From<T>`:
             <u32 as From<Ipv4Addr>>
             <u32 as From<NonZeroU32>>
             <u32 as From<bool>>
             <u32 as From<char>>
             <u32 as From<ring::endian::BigEndian<u32>>>
             <u32 as From<ring::endian::LittleEndian<u32>>>
             <u32 as From<u16>>
             <u32 as From<u8>>
   = note: required for `i32` to implement `Into<u32>`
note: required by a bound in `single`
  --> http\src\client\blocking.rs:72:13
   |
72 |         Id: Into<I>,
   |             ^^^^^^^ required by this bound in `Requester::single`

```
</details>

Let me know if you have other ideas, otherwise it should be good to merge.

**Comment by greaka** [comment]
You just unearthed a bug.
The blocking implementation differs from the async one, because I forgot that `impl Into<I>` there.
I need to have a deeper look into this.

**Comment by greaka** [comment]
Interestingly, this is not an issue when you new-type everything, which I wanted to do eventually anyway.
I think we can merge this for now, but the `next` branch requires some work.

**Pull request merged**
